### ISSUE TITLE
There is an issue. upon first load.

### ISSUE THREAD

**Issue by TlYPN** [FelisDevelopment/fd_storage_support#1]
https://gyazo.com/2916453a6545d771d1f621834c474f58

qtarget WAS started before fd_storage

**Comment by TlYPN** [comment]
also im using the source code version

**Comment by niunisas** [comment]
Hi. Your qtarget might be too old, because error says: No such export, I've tested resource with newest version of qtarget.

**Comment by TlYPN** [comment]
i am on one of the newest versions.

**Comment by TlYPN** [comment]
let me check

**Comment by niunisas** [comment]
Or your resource qtarget resource is named differently?

**Comment by TlYPN** [comment]
So im on 2.0.0 according to the manifest. and the latest seems to be 2.10

**Comment by niunisas** [comment]
Just checked, I've tested it with 2.1.0

**Comment by TlYPN** [comment]
Awesome! ill update my qtarget and get back to you!

**Comment by niunisas** [comment]
Please let me know afterwards.

**Comment by TlYPN** [comment]
absolutely

**Comment by TlYPN** [comment]
So addtargetmodel is fine now but now im have an issue where i cant place anything. heres a video

**Comment by TlYPN** [comment]
https://youtu.be/VPLML2WIsmo

**Comment by niunisas** [comment]
Try putting it in quick slot, I mean 1,2,3,4 or 5, and use it. Same thing happens?

**Comment by niunisas** [comment]
Any error on srv side?

**Comment by TlYPN** [comment]
Okay just did that, no errors on server side. and the same issue happens. and i have the unobfuscated version if that helps

**Comment by niunisas** [comment]
It's really strange. What framework you are using? Hopefully your ac doesnt block anything.

**Comment by TlYPN** [comment]
Esx_legacy, with ox_inventory and qtarget

**Comment by niunisas** [comment]
Ox_inventory newest version? That might be an issue also.

**Comment by TlYPN** [comment]
let me check my version for you

**Comment by TlYPN** [comment]
version      '2.6.1'

**Comment by niunisas** [comment]
Can you update to 2.7.4 and try?

**Comment by TlYPN** [comment]
it is now functioning correctly

**Comment by niunisas** [comment]
Great, I'll close this issue then.
