### ISSUE TITLE
Error in console on first load

### ISSUE THREAD

**Issue by Jackster-2233** [FelisDevelopment/fd_storage_support#2]
https://i.imgur.com/rM1xqcx.png

**Comment by Jackster-2233** [comment]
https://i.imgur.com/smRurUP.png

**Comment by niunisas** [comment]
Speeding. It's really strange, I'll check this issue and update you.

**Comment by niunisas** [comment]
What framework are you using?

**Comment by niunisas** [comment]
And please paste me your config. It's in `shared/config.lua`

**Comment by Jackster-2233** [comment]
Hi,

I’m using qbcore and I have followed the instructions for the core on the documentation site

**Comment by Jackster-2233** [comment]
Config =  {
    debug = true,
    purge_expired_every = 1000 * 60 * 10, -- 10 minutes
    save_storages_every = 1000 * 60 * 10, -- 10 minutes
    distance_between_containers = 5,
    maximum_distance_for_placing = 50,
    hacking = {
        icons = 3,
        time = 5000
    },
    core = {
        framework = 'qbcore', -- available: qbcore, esx
        resource = 'qb-core' -- for qbcore usually: qb-core, for esx usually: es_extended
    },
    animations = {
        destroy = {
            dict = 'anim@amb@clubhouse@tutorial@bkr_tut_ig3@',
            name = 'machinic_loop_mechandplayer',
        },
        repair = {
            dict = 'anim@amb@clubhouse@tutorial@bkr_tut_ig3@',
            name = 'machinic_loop_mechandplayer',
        },
        create = {
            dict = "random@domestic",
            name = "pickup_low"
        },
        lock = {
            dict = 'anim@amb@clubhouse@tutorial@bkr_tut_ig3@',
            name = 'machinic_loop_mechandplayer',
        },
        unlock = {
            dict = 'anim@amb@clubhouse@tutorial@bkr_tut_ig3@',
            name = 'machinic_loop_mechandplayer',
        }
    },
    crates = {
        smallcrate = {
            lifetime = 14 * 86400, -- 7 days
            model = "gr_prop_gr_rsply_crate03a",
            can_pickup = true,
            destroy_time = 30000,
            lock_time = 30000,
            break_time = 30000,
            repair_time = 30000,
            distance = 2,
            repair_kits_needed = 1,
            size = {
                slots = 15,
                weight = 50000
            }
        },
        mediumcrate = {
            lifetime = 14 * 86400, -- 14 days
            model = "prop_box_wood07a",
            destroy_time = 60000,
            lock_time = 30000,
            break_time = 30000,
            repair_time = 30000,
            distance = 2,
            repair_kits_needed = 2,
            size = {
                slots = 30,
                weight = 100000
            }
        },
        bigcrate = {
            lifetime = 30 * 86400, -- 30 days
            model = "prop_box_wood04a",
            destroy_time = 90000,
            lock_time = 30000,
            break_time = 30000,
            repair_time = 30000,
            distance = 2,
            repair_kits_needed = 3,
            size = {
                slots = 50,
                weight = 200000
            }
        },
        smallcontainer = {
            lifetime = 30 * 86400, -- 30 days
            model = "prop_container_05mb",
            destroy_time = 120000,
            lock_time = 30000,
            break_time = 30000,
            repair_time = 30000,
            distance = 3,
            repair_kits_needed = 4,
            size = {
                slots = 100,
                weight = 500000
            }
        },
        mediumcontainer = {
            lifetime = 30 * 86400, -- 30 days
            model = "prop_container_03mb",
            destroy_time = 120000,
            lock_time = 30000,
            break_time = 30000,
            repair_time = 30000,
            distance = 5,
            repair_kits_needed = 5,
            size = {
                slots = 200,
                weight = 1000000
            }
        },
        bigcontainer = {
            lifetime = 30 * 86400, -- 30 days
            model = "prop_container_01mb",
            destroy_time = 120000,
            lock_time = 30000,
            break_time = 30000,
            repair_time = 30000,
            distance = 7,
            repair_kits_needed = 6,
            size = {
                slots = 400,
                weight = 1500000
            }
        },
        smalltrapcrate = {
            lifetime = 30 * 86400, -- 30 days
            model = "gr_prop_gr_rsply_crate03a",
            destroy_time = 30000,
            distance = 3,
            trap = true
        },
        trapcrate = {
            lifetime = 30 * 86400, -- 30 days
            model = "prop_box_wood07a",
            destroy_time = 30000,
            distance = 3,
            trap = true
        },
        bigtrapcrate = {
            lifetime = 30 * 86400, -- 30 days
            model = "prop_box_wood04a",
            destroy_time = 30000,
            distance = 3,
            trap = true
        },
        portablefridge = {
            lifetime = 30 * 86400, -- 30 days
            model = "v_res_tre_fridge",
            destroy_time = 30000,
            distance = 3,
            offset = 0.0,
            size = {
                slots = 20,
                weight = 70000
            }
        }
    }
}

**Comment by niunisas** [comment]
Is your qb-core an old version? Seems like that resource is not getting shared object.

Do you have `GetCoreObject` export in your core?
You can check it here: https://github.com/qbcore-framework/qb-core/blob/cf0de3ed35fc37f12386474cea44ba69cbda980f/server/main.lua#L7

**Comment by Jackster-2233** [comment]
I'm on the most latest version

**Comment by Jackster-2233** [comment]
https://i.imgur.com/pc6bTpr.png

**Comment by niunisas** [comment]
Hmm, strange. I'll try to reproduce error and check it out. Can't promise exact time since tomorrow is Easter. I will give a solution or a fix to this tomorrow or monday latest.

**Comment by Jackster-2233** [comment]
Okay thanks, yeah I understand.

**Comment by Jackster-2233** [comment]
Hey, any updates?

**Comment by niunisas** [comment]
Hi. Looking at it now, will give an update soon.

**Comment by niunisas** [comment]
@Jackster-2233 Please redownload new version from keymaster, everything should work now.

**Comment by Jackster-2233** [comment]
Just trying it now, the initial error has gone

**Comment by Jackster-2233** [comment]
Perfect all working ty

**Comment by niunisas** [comment]
Great.
