### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by CMon1026** [FelisDevelopment/fd_storage_support#4]
when i start server i get this spammed i console. Do you think i missed something or is there an extra step i am missing? i have added all items correctly to qbcore shared items as i can spawn them all in fine. i am on most recent qbcore framework
[      script:qb-core] > ? (@qb-core/server/events.lua:243)
[      script:qb-core] > TriggerCallback (@qb-core/server/functions.lua:220)
[      script:qb-core] > handler (@qb-core/server/events.lua:120)
[      script:qb-core] SCRIPT ERROR: @qb-core/server/events.lua:243: attempt to index a nil value (local 'item')

**Comment by niunisas** [comment]
Not our script issue, submitted an PR to qb-core, for a fix.

https://github.com/qbcore-framework/qb-core/pull/741
